### ISSUE TITLE
How can i upgrade this project for vivado 2017.4 

### ISSUE THREAD

**Issue by Anadelphia** [Digilent/Zybo-Z7-20-HDMI#1]
Hi.
Thanks for your useful project but i cant run you'r project in vivado 2017.4 version, if its possible please show me the way ?
how can i upgrade zybo projects from 2016.4 to 2017.4 

Windows 7.
zybo 7020.
vivado 2017.4

best regards.

**Comment by artvvb** [comment]
Apologies we didn't see this sooner,

Please submit this question to Digilent support at our [forums](https://forum.digilentinc.com).

Thanks,
Arthur

**Comment by Anadelphia** [comment]
Thanks for your replay 
but i fixed the problems, by making a new project without your tcl file and using your source codes
